apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: backend-ingress
spec:
  rules:
  - host: backend
    http:
      paths:
      - backend:
          serviceName: backend-service
          servicePort: 80
