apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-worker-deployment
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
      role: worker
  template:
    metadata:
      labels:
        app: backend
        role: worker
    spec:
      containers:
      - image: registry.openculinary.org/reciperadar/backend
        imagePullPolicy: IfNotPresent
        name: backend
        command: ['/srv/.local/bin/celery']
        args: ['-A', 'reciperadar.workers', 'worker', '-Q', 'celery,crawl_url,crawl_recipe,index_recipe,recrawl_search,recipe_not_found,update_product_synonyms']
        securityContext:
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /var/tmp
          name: var-tmp
      volumes:
      - name: var-tmp
        emptyDir:
          medium: "Memory"
          sizeLimit: "128Mi"
