"""Add image-display toggles on domain and recipe models

Revision ID: 010ac91c77b2
Revises: 4cad42f6e760
Create Date: 2022-11-07 18:07:57.890852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '010ac91c77b2'
down_revision = '4cad42f6e760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domains', sa.Column('image_enabled', sa.Boolean(), nullable=True))
    op.add_column('recipes', sa.Column('image_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'image_enabled')
    op.drop_column('domains', 'image_enabled')
    # ### end Alembic commands ###
