"""Move dietary properties from ingredient model to product model

Revision ID: 06e4193e416f
Revises: cb0dd207d413
Create Date: 2020-10-23 16:43:57.466830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06e4193e416f'
down_revision = 'cb0dd207d413'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient_products', sa.Column('is_dairy_free', sa.Boolean(), nullable=True))
    op.add_column('ingredient_products', sa.Column('is_gluten_free', sa.Boolean(), nullable=True))
    op.add_column('ingredient_products', sa.Column('is_vegan', sa.Boolean(), nullable=True))
    op.add_column('ingredient_products', sa.Column('is_vegetarian', sa.Boolean(), nullable=True))
    op.drop_column('recipe_ingredients', 'is_vegan')
    op.drop_column('recipe_ingredients', 'is_gluten_free')
    op.drop_column('recipe_ingredients', 'is_vegetarian')
    op.drop_column('recipe_ingredients', 'is_dairy_free')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_ingredients', sa.Column('is_dairy_free', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('recipe_ingredients', sa.Column('is_vegetarian', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('recipe_ingredients', sa.Column('is_gluten_free', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('recipe_ingredients', sa.Column('is_vegan', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('ingredient_products', 'is_vegetarian')
    op.drop_column('ingredient_products', 'is_vegan')
    op.drop_column('ingredient_products', 'is_gluten_free')
    op.drop_column('ingredient_products', 'is_dairy_free')
    # ### end Alembic commands ###
