"""Add hash-ids to URL models

Revision ID: 0ed6bcd27647
Revises: a34cbcbedf7c
Create Date: 2023-12-12 18:26:21.409576

"""
from alembic import op
from pymmh3 import hash_bytes
import sqlalchemy as sa

from reciperadar.models.url import BaseURL


# revision identifiers, used by Alembic.
revision = '0ed6bcd27647'
down_revision = 'a34cbcbedf7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crawl_urls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.String(), nullable=True))

    with op.batch_alter_table('recipe_urls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.String(), nullable=True))

    # ### end Alembic commands ###

    connection = op.get_bind()

    records = connection.execute(sa.text('SELECT url FROM crawl_urls'))
    for (url,) in records.fetchall():
        generated_id = BaseURL.generate_id(hash_bytes(url).encode("utf-8"))
        connection.execute(
            sa.text('UPDATE crawl_urls SET id = :generated_id WHERE url = :url'),
            parameters={"generated_id": generated_id, "url": url},
        )

    records = connection.execute(sa.text('SELECT url FROM recipe_urls'))
    for (url,) in records.fetchall():
        generated_id = BaseURL.generate_id(hash_bytes(url).encode("utf-8"))
        connection.execute(
            sa.text('UPDATE recipe_urls SET id = :generated_id WHERE url = :url'),
            parameters={"generated_id": generated_id, "url": url},
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_urls', schema=None) as batch_op:
        batch_op.drop_column('id')

    with op.batch_alter_table('crawl_urls', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
