"""Domains: remap TLDs to FQDNs

Revision ID: 11742ee5cedb
Revises: 8255e4e6e956
Create Date: 2025-01-10 23:06:23.137184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11742ee5cedb'
down_revision = '8255e4e6e956'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
        -- Compare existing TLDs with extracted FQDNs
        CREATE TEMPORARY TABLE remappings (tld, domain) AS
        SELECT DISTINCT
          domain AS tld,
          (string_to_array(dst, '/'))[3] as domain  -- http: ||| www.domain.test | path | to | index.html
        FROM recipes;

        -- Create FQDNs where they differ from existing TLD configuration records
        INSERT INTO domains (domain, contact, approval, approved_at, crawl_enabled, cache_enabled)
        SELECT m.domain, d.contact, d.approval, d.approved_at, d.crawl_enabled, d.cache_enabled
        FROM domains AS d
        JOIN remappings AS m ON m.tld = d.domain
        WHERE m.tld <> m.domain;

        -- Delete orphaned TLD configuration records
        DELETE FROM domains AS d
        WHERE NOT EXISTS
        (
            SELECT *
            FROM remappings AS m
            WHERE m.domain = d.domain
        );
    ''')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
