"""redirections

Revision ID: 1282ece687fa
Revises: 23bd350b0052
Create Date: 2023-08-10 10:52:51.877155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1282ece687fa'
down_revision = '23bd350b0052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('redirected_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('redirected_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('recipes_redirected_id_fkey', 'recipes', ['redirected_id'], ['id'], onupdate='cascade', ondelete='cascade', deferrable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_constraint('recipes_redirected_id_fkey', type_='foreignkey')
        batch_op.drop_column('redirected_at')
        batch_op.drop_column('redirected_id')

    # ### end Alembic commands ###
