"""Remove redundant IngredientProduct columns

Revision ID: 2791152d332f
Revises: 81e3a09dcbc9
Create Date: 2020-11-17 20:59:02.506259

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2791152d332f'
down_revision = '81e3a09dcbc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredient_products', 'is_dairy_free')
    op.drop_column('ingredient_products', 'singular')
    op.drop_column('ingredient_products', 'is_kitchen_staple')
    op.drop_column('ingredient_products', 'plural')
    op.drop_column('ingredient_products', 'is_vegetarian')
    op.drop_column('ingredient_products', 'is_vegan')
    op.drop_column('ingredient_products', 'product')
    op.drop_column('ingredient_products', 'is_gluten_free')
    op.drop_column('ingredient_products', 'category')
    op.drop_column('ingredient_products', 'contents')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient_products', sa.Column('contents', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('ingredient_products', sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ingredient_products', sa.Column('is_gluten_free', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('ingredient_products', sa.Column('product', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ingredient_products', sa.Column('is_vegan', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('ingredient_products', sa.Column('is_vegetarian', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('ingredient_products', sa.Column('plural', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ingredient_products', sa.Column('is_kitchen_staple', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('ingredient_products', sa.Column('singular', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ingredient_products', sa.Column('is_dairy_free', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
