"""Add domain model to database

Revision ID: 2dcfe8ba6fd5
Revises: 9f00ae29338d
Create Date: 2020-10-16 11:49:53.724830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dcfe8ba6fd5'
down_revision = '9f00ae29338d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domains',
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('image_src', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('domain')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('domains')
    # ### end Alembic commands ###
