"""Use product_name.id column as primary key

Revision ID: 427246ce37f3
Revises: 5cf3dad08c70
Create Date: 2022-07-20 12:12:00.241501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '427246ce37f3'
down_revision = '5cf3dad08c70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_names_pkey', 'product_names')
    op.alter_column('product_names', 'id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('product_names', 'product_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('product_names', 'singular',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_product_names_product_id'), 'product_names', ['product_id'], unique=False)
    op.create_primary_key('product_names_pkey', 'product_names', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_names_pkey', 'product_names')
    op.drop_index(op.f('ix_product_names_product_id'), table_name='product_names')
    op.alter_column('product_names', 'singular',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('product_names', 'product_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('product_names', 'id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_primary_key('product_names_pkey', 'product_names', ['product_id', 'singular'])
    # ### end Alembic commands ###
