"""Add earliest_crawled_at, latest_crawled_at URL metadata fields

Revision ID: 47fdb7760985
Revises: ba2a7ae67226
Create Date: 2022-07-29 13:03:35.563569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47fdb7760985'
down_revision = 'ba2a7ae67226'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawl_urls', sa.Column('earliest_crawled_at', sa.DateTime(), nullable=True))
    op.add_column('crawl_urls', sa.Column('latest_crawled_at', sa.DateTime(), nullable=True))
    op.add_column('recipe_urls', sa.Column('earliest_crawled_at', sa.DateTime(), nullable=True))
    op.add_column('recipe_urls', sa.Column('latest_crawled_at', sa.DateTime(), nullable=True))
    op.execute('''
        update crawl_urls
        set earliest_crawled_at = crawled_at, latest_crawled_at = crawled_at
    ''')
    op.execute('''
        update recipe_urls
        set earliest_crawled_at = crawled_at, latest_crawled_at = crawled_at
    ''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_urls', 'latest_crawled_at')
    op.drop_column('recipe_urls', 'earliest_crawled_at')
    op.drop_column('crawl_urls', 'latest_crawled_at')
    op.drop_column('crawl_urls', 'earliest_crawled_at')
    # ### end Alembic commands ###
