"""Allow nullable URL for URL records

Revision ID: 4952a0d12844
Revises: dbf4e681d464
Create Date: 2025-02-04 15:24:53.729528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4952a0d12844'
down_revision = 'dbf4e681d464'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crawl_urls', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('recipe_urls', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_urls', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('crawl_urls', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
