"""Cleanup: remove recipe directions model

Revision ID: 506f652b919e
Revises: 638dc7ffe180
Create Date: 2024-12-18 22:22:33.792603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '506f652b919e'
down_revision = '638dc7ffe180'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_directions', schema=None) as batch_op:
        batch_op.drop_index('ix_recipe_directions_recipe_id')

    op.drop_table('direction_equipment')
    op.drop_table('recipe_directions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_directions',
    sa.Column('recipe_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('markup', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name='recipe_directions_recipe_id_fkey', onupdate='CASCADE', ondelete='CASCADE', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='recipe_directions_pkey')
    )

    with op.batch_alter_table('recipe_directions', schema=None) as batch_op:
        batch_op.create_index('ix_recipe_directions_recipe_id', ['recipe_id'], unique=False)
    op.create_table('direction_equipment',
    sa.Column('direction_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['direction_id'], ['recipe_directions.id'], name='direction_equipment_direction_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='direction_equipment_pkey')
    )
    with op.batch_alter_table('direction_equipment', schema=None) as batch_op:
        batch_op.create_index('ix_direction_equipment_direction_id', ['direction_id'], unique=False)
    # ### end Alembic commands ###
