"""Add recipe_ingredients.relative_density column

Revision ID: 518a3792bb67
Revises: c8683f781ac5
Create Date: 2020-10-14 18:15:06.166712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '518a3792bb67'
down_revision = 'c8683f781ac5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_ingredients', sa.Column('relative_density', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_ingredients', 'relative_density')
    # ### end Alembic commands ###
