"""Drop url.crawled_at column

Revision ID: 58641e07557c
Revises: 47fdb7760985
Create Date: 2022-07-29 14:05:51.742618

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '58641e07557c'
down_revision = '47fdb7760985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crawl_urls', 'crawled_at')
    op.drop_column('recipe_urls', 'crawled_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_urls', sa.Column('crawled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('crawl_urls', sa.Column('crawled_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
