"""Introduce product_name.id column

Revision ID: 5cf3dad08c70
Revises: bb9f16941512
Create Date: 2022-07-20 11:12:33.803756

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session

from reciperadar.models.recipes.product import ProductName


# revision identifiers, used by Alembic.
revision = '5cf3dad08c70'
down_revision = 'bb9f16941512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_names', sa.Column('id', sa.String(), nullable=True))

    session = Session(bind=op.get_bind())
    for record in session.query(ProductName):
        record.id = ProductName.generate_id()
    session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_names', 'id')
    # ### end Alembic commands ###


def data_upgrades():
    raise Exception()
