"""Introduce product_name.id column

Revision ID: 5cf3dad08c70
Revises: bb9f16941512
Create Date: 2022-07-20 11:12:33.803756

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session
from sqlalchemy.sql import text

from reciperadar.models.recipes.product import ProductName


# revision identifiers, used by Alembic.
revision = '5cf3dad08c70'
down_revision = 'bb9f16941512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_names', sa.Column('id', sa.String(), nullable=True, default=ProductName.generate_id))

    ## connection = op.get_bind()
    ## records = connection.execute('SELECT product_id, singular from product_names')
    ## for r in records.fetchall():
    ##    product_id, singular = r
    ##    connection.execute(
    ##        text('UPDATE product_names SET id = :generated_id WHERE product_id = :product_id AND singular = :singular'),
    ##         generated_id=ProductName.generate_id(),
    ##        product_id=product_id,
    ##        singular=singular,
    ##    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_names', 'id')
    # ### end Alembic commands ###


def data_upgrades():
    raise Exception()
