"""Add nutrition units fields

Revision ID: 5ea49f29eac2
Revises: 9c1f15154352
Create Date: 2020-12-17 15:53:20.378001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ea49f29eac2'
down_revision = '9c1f15154352'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient_nutrition', sa.Column('carbohydrates_units', sa.String(), nullable=True))
    op.add_column('ingredient_nutrition', sa.Column('energy_units', sa.String(), nullable=True))
    op.add_column('ingredient_nutrition', sa.Column('fat_units', sa.String(), nullable=True))
    op.add_column('ingredient_nutrition', sa.Column('fibre_units', sa.String(), nullable=True))
    op.add_column('ingredient_nutrition', sa.Column('protein_units', sa.String(), nullable=True))
    op.add_column('product_nutrition', sa.Column('carbohydrates_units', sa.String(), nullable=True))
    op.add_column('product_nutrition', sa.Column('energy_units', sa.String(), nullable=True))
    op.add_column('product_nutrition', sa.Column('fat_units', sa.String(), nullable=True))
    op.add_column('product_nutrition', sa.Column('fibre_units', sa.String(), nullable=True))
    op.add_column('product_nutrition', sa.Column('protein_units', sa.String(), nullable=True))
    op.add_column('recipe_nutrition', sa.Column('carbohydrates_units', sa.String(), nullable=True))
    op.add_column('recipe_nutrition', sa.Column('energy_units', sa.String(), nullable=True))
    op.add_column('recipe_nutrition', sa.Column('fat_units', sa.String(), nullable=True))
    op.add_column('recipe_nutrition', sa.Column('fibre_units', sa.String(), nullable=True))
    op.add_column('recipe_nutrition', sa.Column('protein_units', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_nutrition', 'protein_units')
    op.drop_column('recipe_nutrition', 'fibre_units')
    op.drop_column('recipe_nutrition', 'fat_units')
    op.drop_column('recipe_nutrition', 'energy_units')
    op.drop_column('recipe_nutrition', 'carbohydrates_units')
    op.drop_column('product_nutrition', 'protein_units')
    op.drop_column('product_nutrition', 'fibre_units')
    op.drop_column('product_nutrition', 'fat_units')
    op.drop_column('product_nutrition', 'energy_units')
    op.drop_column('product_nutrition', 'carbohydrates_units')
    op.drop_column('ingredient_nutrition', 'protein_units')
    op.drop_column('ingredient_nutrition', 'fibre_units')
    op.drop_column('ingredient_nutrition', 'fat_units')
    op.drop_column('ingredient_nutrition', 'energy_units')
    op.drop_column('ingredient_nutrition', 'carbohydrates_units')
    # ### end Alembic commands ###
