"""Product ID deletion and update cascades

Revision ID: 5f9434f36fd1
Revises: 68de5915526d
Create Date: 2022-06-22 18:26:24.358215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f9434f36fd1'
down_revision = '68de5915526d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_nutrition_product_id_fkey', 'product_nutrition', type_='foreignkey')
    op.create_foreign_key(None, 'product_nutrition', 'products', ['product_id'], ['id'], onupdate='cascade', ondelete='cascade', deferrable=True)
    op.drop_constraint('products_parent_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'products', ['parent_id'], ['id'], onupdate='cascade', ondelete='cascade', deferrable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_parent_id_fkey', 'products', 'products', ['parent_id'], ['id'], deferrable=True)
    op.drop_constraint(None, 'product_nutrition', type_='foreignkey')
    op.create_foreign_key('product_nutrition_product_id_fkey', 'product_nutrition', 'products', ['product_id'], ['id'], ondelete='CASCADE', deferrable=True)
    # ### end Alembic commands ###
