"""Add per-domain contact info to the database schema

Revision ID: 5fbd36138e69
Revises: 010ac91c77b2
Create Date: 2022-11-17 15:05:42.429054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fbd36138e69'
down_revision = '010ac91c77b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domains', sa.Column('contact', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('domains', 'contact')
    # ### end Alembic commands ###
