"""Remove recipe website images

Revision ID: 638dc7ffe180
Revises: 284240c560f2
Create Date: 2024-12-17 13:31:48.813069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '638dc7ffe180'
down_revision = '284240c560f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('domains', schema=None) as batch_op:
        batch_op.drop_column('image_enabled')
        batch_op.drop_column('image_src')

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('image_enabled')
        batch_op.drop_column('image_src')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_src', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('image_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True))

    with op.batch_alter_table('domains', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_src', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('image_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
