"""Enable ingredient_products.product_id -> products.id foreign key

Revision ID: 63e8f3fa5988
Revises: df53b10fe203
Create Date: 2020-11-16 22:52:23.189907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63e8f3fa5988'
down_revision = 'e4c7d98b0536'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ingredient_products_product_id'), 'ingredient_products', ['product_id'], unique=False)
    op.create_foreign_key('ingredient_products_product_id_fkey', 'ingredient_products', 'products', ['product_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ingredient_products_product_id_fkey', 'ingredient_products', type_='foreignkey')
    op.drop_index(op.f('ix_ingredient_products_product_id'), table_name='ingredient_products')
    # ### end Alembic commands ###
