"""Add per-domain approval fields

Revision ID: 65710cf38339
Revises: 5fbd36138e69
Create Date: 2022-11-17 16:28:28.800534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65710cf38339'
down_revision = '5fbd36138e69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domains', sa.Column('approval', sa.String(), nullable=True))
    op.add_column('domains', sa.Column('approved_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('domains', 'approved_at')
    op.drop_column('domains', 'approval')
    # ### end Alembic commands ###
