"""Allow deletion cascades from recipe products to product nutrition

Revision ID: 68de5915526d
Revises: a061b3526863
Create Date: 2022-05-23 19:49:22.387271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68de5915526d'
down_revision = 'a061b3526863'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_nutrition_product_id_fkey', 'product_nutrition', type_='foreignkey')
    op.create_foreign_key(None, 'product_nutrition', 'products', ['product_id'], ['id'], ondelete='cascade', deferrable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_nutrition', type_='foreignkey')
    op.create_foreign_key('product_nutrition_product_id_fkey', 'product_nutrition', 'products', ['product_id'], ['id'], deferrable=True)
    # ### end Alembic commands ###
