"""Replace 'appliance', 'utensil' and 'vessel' models with a single 'equipment' model

Revision ID: 6b187bc74d7a
Revises: 5ea49f29eac2
Create Date: 2021-02-25 11:11:19.423230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b187bc74d7a'
down_revision = '5ea49f29eac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direction_equipment',
    sa.Column('direction_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['direction_id'], ['recipe_directions.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_direction_equipment_direction_id'), 'direction_equipment', ['direction_id'], unique=False)
    op.execute('''
        insert into direction_equipment (direction_id, id, name, category)
        select direction_id, id, appliance, 'appliance' from direction_appliances
        union all
        select direction_id, id, utensil, 'utensil' from direction_utensils
        union all
        select direction_id, id, vessel, 'vessel' from direction_vessels
    ''')
    op.drop_index('ix_direction_appliances_direction_id', table_name='direction_appliances')
    op.drop_table('direction_appliances')
    op.drop_index('ix_direction_utensils_direction_id', table_name='direction_utensils')
    op.drop_table('direction_utensils')
    op.drop_index('ix_direction_vessels_direction_id', table_name='direction_vessels')
    op.drop_table('direction_vessels')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direction_vessels',
    sa.Column('direction_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('vessel', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['direction_id'], ['recipe_directions.id'], name='direction_vessels_direction_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='direction_vessels_pkey')
    )
    op.create_index('ix_direction_vessels_direction_id', 'direction_vessels', ['direction_id'], unique=False)
    op.create_table('direction_utensils',
    sa.Column('direction_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('utensil', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['direction_id'], ['recipe_directions.id'], name='direction_utensils_direction_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='direction_utensils_pkey')
    )
    op.create_index('ix_direction_utensils_direction_id', 'direction_utensils', ['direction_id'], unique=False)
    op.create_table('direction_appliances',
    sa.Column('direction_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('appliance', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['direction_id'], ['recipe_directions.id'], name='direction_appliances_direction_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='direction_appliances_pkey')
    )
    op.create_index('ix_direction_appliances_direction_id', 'direction_appliances', ['direction_id'], unique=False)
    op.execute('''
        insert into direction_appliances (direction_id, id, appliance)
        select direction_id, id, category from direction_equipment
        where category = 'appliance'
    ''')
    op.execute('''
        insert into direction_utensils (direction_id, id, utensil)
        select direction_id, id, category from direction_equipment
        where category = 'utensil'
    ''')
    op.execute('''
        insert into direction_vessels (direction_id, id, vessel)
        select direction_id, id, category from direction_equipment
        where category = 'vessel'
    ''')
    op.drop_index(op.f('ix_direction_equipment_direction_id'), table_name='direction_equipment')
    op.drop_table('direction_equipment')
    # ### end Alembic commands ###
