"""Add product property columns to RecipeIngredient model

Revision ID: 80af893c0415
Revises: 2791152d332f
Create Date: 2020-11-18 14:27:59.666273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80af893c0415'
down_revision = '2791152d332f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_ingredients', sa.Column('product_id', sa.String(), nullable=True))
    op.add_column('recipe_ingredients', sa.Column('product_is_plural', sa.Boolean(), nullable=True))
    op.add_column('recipe_ingredients', sa.Column('product_parser', sa.String(), nullable=True))
    op.execute('''
        update recipe_ingredients
        set
            product_id = ip.product_id,
            product_is_plural = ip.is_plural,
            product_parser = ip.product_parser
        from ingredient_products as ip
        where ip.ingredient_id = recipe_ingredients.id
    ''')
    op.create_index(op.f('ix_recipe_ingredients_product_id'), 'recipe_ingredients', ['product_id'], unique=False)
    op.create_foreign_key('recipe_ingredients_product_id_fkey', 'recipe_ingredients', 'products', ['product_id'], ['id'], deferrable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('recipe_ingredients_product_id_fkey', 'recipe_ingredients', type_='foreignkey')
    op.drop_index(op.f('ix_recipe_ingredients_product_id'), table_name='recipe_ingredients')
    op.drop_column('recipe_ingredients', 'product_parser')
    op.drop_column('recipe_ingredients', 'product_is_plural')
    op.drop_column('recipe_ingredients', 'product_id')
    # ### end Alembic commands ###
