"""Allow product foreign key references to be deferred

Revision ID: 8742627bf204
Revises: 63e8f3fa5988
Create Date: 2020-11-17 10:30:04.340268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8742627bf204'
down_revision = '63e8f3fa5988'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ingredient_products_product_id_fkey', 'ingredient_products', type_='foreignkey')
    op.create_foreign_key('ingredient_products_product_id_fkey', 'ingredient_products', 'products', ['product_id'], ['id'], deferrable=True)
    op.drop_constraint('product_nutrition_product_id_fkey', 'product_nutrition', type_='foreignkey')
    op.create_foreign_key('product_nutrition_product_id_fkey', 'product_nutrition', 'products', ['product_id'], ['id'], deferrable=True)
    op.drop_constraint('products_parent_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key('products_parent_id_fkey', 'products', 'products', ['parent_id'], ['id'], deferrable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_nutrition_product_id_fkey', 'product_nutrition', type_='foreignkey')
    op.create_foreign_key('product_nutrition_product_id_fkey', 'product_nutrition', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('ingredient_products_product_id_fkey', 'ingredient_products', type_='foreignkey')
    op.create_foreign_key('ingredient_products_product_id_fkey', 'ingredient_products', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('products_parent_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key('products_parent_id_fkey', 'products', 'products', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
