"""add crawler_version column to crawl-related tables

Revision ID: 8763d112afd0
Revises: 8f39b3c75033
Create Date: 2020-07-10 13:40:36.037650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8763d112afd0'
down_revision = '8f39b3c75033'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawl_urls', sa.Column('crawler_version', sa.String(), nullable=True))
    op.add_column('recipe_urls', sa.Column('crawler_version', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_urls', 'crawler_version')
    op.drop_column('crawl_urls', 'crawler_version')
    # ### end Alembic commands ###
