"""Allow product deletions to 'set null'; allow product key updates to cascade

Revision ID: 9c1f15154352
Revises: 3b29701d26ca
Create Date: 2020-11-23 21:15:36.197067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c1f15154352'
down_revision = '3b29701d26ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('recipe_ingredients_product_id_fkey', 'recipe_ingredients', type_='foreignkey')
    op.create_foreign_key('recipe_ingredients_product_id_fkey', 'recipe_ingredients', 'products', ['product_id'], ['id'], onupdate='cascade', ondelete='set null', deferrable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('recipe_ingredients_product_id_fkey', 'recipe_ingredients', type_='foreignkey')
    op.create_foreign_key('recipe_ingredients_product_id_fkey', 'recipe_ingredients', 'products', ['product_id'], ['id'], deferrable=True)
    # ### end Alembic commands ###
