"""Add dietary properties to ingredient model

Revision ID: 9f00ae29338d
Revises: 518a3792bb67
Create Date: 2020-10-15 19:45:29.189613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f00ae29338d'
down_revision = '518a3792bb67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_ingredients', sa.Column('is_dairy_free', sa.Boolean(), nullable=True))
    op.add_column('recipe_ingredients', sa.Column('is_gluten_free', sa.Boolean(), nullable=True))
    op.add_column('recipe_ingredients', sa.Column('is_vegan', sa.Boolean(), nullable=True))
    op.add_column('recipe_ingredients', sa.Column('is_vegetarian', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_ingredients', 'is_vegetarian')
    op.drop_column('recipe_ingredients', 'is_vegan')
    op.drop_column('recipe_ingredients', 'is_gluten_free')
    op.drop_column('recipe_ingredients', 'is_dairy_free')
    # ### end Alembic commands ###
