"""Allow recipe fk update cascades

Revision ID: a34cbcbedf7c
Revises: 1282ece687fa
Create Date: 2023-12-12 12:56:24.069804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a34cbcbedf7c'
down_revision = '1282ece687fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_directions', schema=None) as batch_op:
        batch_op.drop_constraint('recipe_directions_recipe_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'recipes', ['recipe_id'], ['id'], onupdate='cascade', ondelete='cascade', deferrable=True)

    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.drop_constraint('recipe_ingredients_recipe_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'recipes', ['recipe_id'], ['id'], onupdate='cascade', ondelete='cascade', deferrable=True)

    with op.batch_alter_table('recipe_nutrition', schema=None) as batch_op:
        batch_op.drop_constraint('recipe_nutrition_recipe_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'recipes', ['recipe_id'], ['id'], onupdate='cascade', ondelete='cascade', deferrable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_nutrition', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('recipe_nutrition_recipe_id_fkey', 'recipes', ['recipe_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('recipe_ingredients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('recipe_ingredients_recipe_id_fkey', 'recipes', ['recipe_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('recipe_directions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('recipe_directions_recipe_id_fkey', 'recipes', ['recipe_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
