"""Add Recipe.not_found boolean column.

Revision ID: a948d5986c91
Revises: 330fe0f5e304
Create Date: 2024-04-15 15:37:24.375448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a948d5986c91'
down_revision = '330fe0f5e304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('not_found', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('not_found')

    # ### end Alembic commands ###
