"""Drop product.singular, product.plural columns

Revision ID: b2065825f348
Revises: e7443c70d13d
Create Date: 2022-07-27 15:13:27.349817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2065825f348'
down_revision = 'e7443c70d13d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'singular')
    op.drop_column('products', 'plural')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('plural', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('singular', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
