"""Drop index on RecipeURL.recipe_scrapers_version

Revision ID: ba2a7ae67226
Revises: b2065825f348
Create Date: 2022-07-29 12:13:43.159970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba2a7ae67226'
down_revision = 'b2065825f348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recipe_urls_recipe_scrapers_version', table_name='recipe_urls')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_recipe_urls_recipe_scrapers_version', 'recipe_urls', ['recipe_scrapers_version'], unique=False)
    # ### end Alembic commands ###
