"""Add Wikidata QID to ingredient product model

Revision ID: ba4c68100f65
Revises: a5fba089b17a
Create Date: 2022-08-29 17:04:27.145997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba4c68100f65'
down_revision = 'a5fba089b17a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('wdqid', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'wdqid')
    # ### end Alembic commands ###
