"""Introduce many-product-names-to-one-product into the database schema

Revision ID: bb9f16941512
Revises: 5f9434f36fd1
Create Date: 2022-07-18 19:30:00.583886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb9f16941512'
down_revision = '5f9434f36fd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_names',
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('singular', sa.String(), nullable=False),
    sa.Column('plural', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], onupdate='cascade', ondelete='cascade', deferrable=True),
    sa.PrimaryKeyConstraint('product_id', 'singular', name='product_names_pkey')
    )
    op.execute('''
        insert into product_names (product_id, singular, plural)
        select
            p.id,
            p.singular,
            p.plural
        from products as p
    ''')
    op.create_index(op.f('ix_product_names_singular'), 'product_names', ['singular'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_names_singular'), table_name='product_names')
    op.drop_table('product_names')
    # ### end Alembic commands ###
