"""Allow product foreign key references to be deferred (continued)

Revision ID: bc84259ca6bc
Revises: 8742627bf204
Create Date: 2020-11-17 10:40:48.153813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc84259ca6bc'
down_revision = '8742627bf204'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_parent_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'products', ['parent_id'], ['id'], deferrable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_parent_id_fkey', 'products', 'products', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
