"""Add nutrition database model

Revision ID: c8683f781ac5
Revises: 25510cef242c
Create Date: 2020-10-12 13:54:56.468563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8683f781ac5'
down_revision = '25510cef242c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient_nutrition',
    sa.Column('ingredient_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('carbohydrates', sa.Float(), nullable=True),
    sa.Column('energy', sa.Float(), nullable=True),
    sa.Column('fat', sa.Float(), nullable=True),
    sa.Column('fibre', sa.Float(), nullable=True),
    sa.Column('protein', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['recipe_ingredients.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredient_nutrition_ingredient_id'), 'ingredient_nutrition', ['ingredient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ingredient_nutrition_ingredient_id'), table_name='ingredient_nutrition')
    op.drop_table('ingredient_nutrition')
    # ### end Alembic commands ###
