"""Add author, author_url fields to recipe model

Revision ID: cb0dd207d413
Revises: 2dcfe8ba6fd5
Create Date: 2020-10-21 10:48:36.208052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb0dd207d413'
down_revision = '2dcfe8ba6fd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('author', sa.String(), nullable=True))
    op.add_column('recipes', sa.Column('author_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'author_url')
    op.drop_column('recipes', 'author')
    # ### end Alembic commands ###
