"""Migrate URL primary key from URL to hash-ID

Revision ID: dbf4e681d464
Revises: c203d0dee7e9
Create Date: 2025-02-04 15:04:54.924094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbf4e681d464'
down_revision = 'c203d0dee7e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crawl_urls', schema=None) as batch_op:
        batch_op.drop_index('ix_crawl_urls_id')
        batch_op.create_index(batch_op.f('ix_crawl_urls_url'), ['url'], unique=True)

    with op.batch_alter_table('recipe_urls', schema=None) as batch_op:
        batch_op.drop_index('ix_recipe_urls_id')
        batch_op.create_index(batch_op.f('ix_recipe_urls_url'), ['url'], unique=True)

    # ### end Alembic commands ###

    op.execute('''
        BEGIN TRANSACTION;

        ALTER TABLE crawl_urls DROP CONSTRAINT crawl_urls_pkey;
        ALTER TABLE crawl_urls ADD CONSTRAINT crawl_urls_pkey PRIMARY KEY (id);

        ALTER TABLE recipe_urls DROP CONSTRAINT recipe_urls_pkey;
        ALTER TABLE recipe_urls ADD CONSTRAINT recipe_urls_pkey PRIMARY KEY (id);

        COMMIT TRANSACTION;
    ''')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_urls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_urls_url'))
        batch_op.create_index('ix_recipe_urls_id', ['id'], unique=False)

    with op.batch_alter_table('crawl_urls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crawl_urls_url'))
        batch_op.create_index('ix_crawl_urls_id', ['id'], unique=False)

    # ### end Alembic commands ###

    op.execute('''
        BEGIN TRANSACTION;

        ALTER TABLE crawl_urls DROP CONSTRAINT crawl_urls_pkey;
        ALTER TABLE crawl_urls ADD CONSTRAINT crawl_urls_pkey PRIMARY KEY (url);

        ALTER TABLE recipe_urls DROP CONSTRAINT recipe_urls_pkey;
        ALTER TABLE recipe_urls ADD CONSTRAINT recipe_urls_pkey PRIMARY KEY (url);

        COMMIT TRANSACTION;
    ''')
