"""Drop ingredient.product foreign key

Revision ID: e7443c70d13d
Revises: ebab49f43259
Create Date: 2022-07-27 12:21:06.217922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7443c70d13d'
down_revision = 'ebab49f43259'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recipe_ingredients_product_id', table_name='recipe_ingredients')
    op.drop_constraint('recipe_ingredients_product_id_fkey', 'recipe_ingredients', type_='foreignkey')
    op.drop_column('recipe_ingredients', 'product_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_ingredients', sa.Column('product_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('recipe_ingredients_product_id_fkey', 'recipe_ingredients', 'products', ['product_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL', deferrable=True)
    op.create_index('ix_recipe_ingredients_product_id', 'recipe_ingredients', ['product_id'], unique=False)
    # ### end Alembic commands ###
