"""Add recipe nutrition table

Revision ID: e969eb1efa75
Revises: c696855f1023
Create Date: 2020-10-22 14:18:20.045012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e969eb1efa75'
down_revision = 'c696855f1023'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_nutrition',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('carbohydrates', sa.Float(), nullable=True),
    sa.Column('energy', sa.Float(), nullable=True),
    sa.Column('fat', sa.Float(), nullable=True),
    sa.Column('fibre', sa.Float(), nullable=True),
    sa.Column('protein', sa.Float(), nullable=True),
    sa.Column('recipe_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_nutrition_recipe_id'), 'recipe_nutrition', ['recipe_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipe_nutrition_recipe_id'), table_name='recipe_nutrition')
    op.drop_table('recipe_nutrition')
    # ### end Alembic commands ###
