"""Add product.product_name relationship

Revision ID: ebab49f43259
Revises: 427246ce37f3
Create Date: 2022-07-21 19:03:48.434994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebab49f43259'
down_revision = '427246ce37f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_ingredients', sa.Column('product_name_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_recipe_ingredients_product_name_id'), 'recipe_ingredients', ['product_name_id'], unique=False)
    op.create_foreign_key('recipe_ingredients_product_name_id_fkey', 'recipe_ingredients', 'product_names', ['product_name_id'], ['id'], ondelete='set null', deferrable=True)
    op.execute('''
        update recipe_ingredients
        set product_name_id = pn.id
        from products as p
        join product_names as pn on pn.product_id = p.id
        where recipe_ingredients.product_id = p.id
    ''')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('recipe_ingredients_product_name_id_fkey', 'recipe_ingredients', type_='foreignkey')
    op.drop_index(op.f('ix_recipe_ingredients_product_name_id'), table_name='recipe_ingredients')
    op.drop_column('recipe_ingredients', 'product_name_id')
    # ### end Alembic commands ###
